# Generated by Django 6.0.2 on 2026-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('discount', 'Percentage'), ('regular', 'Fixed')], default='discount', max_length=10),
        ),
    ]
